apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  namespace: lrfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: lrfrontend
        image: aakashrawat1910/learnerreport:frontendforkubernetes
        ports:
        - containerPort: 80      
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: PORT
          value: "3000"
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: fe-secret
              key: REACT_APP_BACKEND_URL