apiVersion: v1
kind: Secret
metadata:
  name: fe-secret
  namespace: lrfrontend
type: Opaque
data:
  REACT_APP_BACKEND_URL: aHR0cDovL2E0YzVhOGI5ZmU5NzA0YmU1OTlmY2NkMmQ5OGQ5ZWIxLTIxMDY5NjUzMzcudXMtd2VzdC0xLmVsYi5hbWF6b25hd3MuY29tOjMwMDE=

  #http://be-service.lrdatabase.svc.cluster.local:3001
  #aHR0cDovL2JlLXNlcnZpY2UubHJiYWNrZW5kLnNzYy5jbHVzdGVyLmxvY2FsOjMzMDAx
  
  #192.168.0.10:3001
  #MTkyLjE2OC4wLjEwOjMwMDE=
  
  #http://192.168.0.10:3001
  #aHR0cDovLzE5Mi4xNjguMC4xMDozMDAx
  
  #aHR0cDovL2xvY2FsaG9zdDozMDAx

 #mongodb://be-service.tmdatabase.svc.cluster.local:27017/travelmemory
  # Base64 encoded URL (http://localhost:3001)

#http://be-service.lrbackend.svc.cluster.local:3001
#aHR0cDovL2JlLXNlcnZpY2UubHJiYWNrZW5kLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDE=

