apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  namespace: lrbackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: lrbackend
        image: aakashrawat1910/learnerreport:backend
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: ATLAS_URI
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: ATLAS_URI
        - name: HASH_KEY
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: HASH_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: JWT_SECRET_KEY          
